### ISSUE TITLE
OMB_MPI apps 

### ISSUE THREAD

**Issue by Zitagcc** [simgrid/SMPI-proxy-apps#8]
+ cd OMB_MPI/
+ echo Configure it
Configure it
+ SMPI_PRETEND_CC=1 ./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking for mpicc... no
checking for oshcc... no
checking for upcc... no
configure: error: in `/home/ci/workspace/SMPI-proxy-apps/Benchmarks/Trinity-Nersc/OMB_MPI':
configure: error: no acceptable C compiler found in $PATH
See `config.log' for more details
--
the full execution report could be found here :  [https://ci.inria.fr/simgrid/job/SMPI-proxy-apps/lastCompletedBuild/testReport/(root)/TestSuite/Trinity_OMB_MPI_pt2pt/](url)

**Comment by adegomme** [comment]
Hi,

using SMPI_PRETEND_CC=1 ./configure CC=smpicc helps a bit, but still
crashes. It's indeed weird.

SMPI_PRETEND_CC=1 ./configure CC=smpicc --host test
finishes configure phase (by faking cross compilation). But it still fails
compilation later with  undefined reference to `rpl_malloc' because we are
pretending to be cross-compiling...

To avoid this an option is to comment out "AC_FUNC_MALLOC" in configure.ac
file, and run "autoreconf -vfi" before everything else .. It allow
compilation to finish, but that's not ideal. I don't understand why
SMPI_PRETEND_CC is still failing, and configure fails to say exactly what
program it tries to compile, which doesn't help debugging.




2018-03-21 16:25 GMT+01:00 Zitagcc <notifications@github.com>:

**Comment by mquinson** [comment]
All the informations you want (and also the other ones) are in config.log

**Comment by mquinson** [comment]
Ok, I take it back. I fail to see what program it compiles...

**Comment by adegomme** [comment]
Martin fixed the issue with SMPI_PRETEND_CC not working in https://github.com/simgrid/simgrid/commit/559da81e5a72b2dca56ccb686739650386b5b89e and OMB tests are now configured properly with smpicc and working . Closing.
